spring:
  profiles:
    active: @spring.profiles.active@
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      jdbc:
        lob.non_contextual_creation: true
server:
  contextPath: /ubanh-status-share
  port: 8080
---
spring:
  profiles: local
  flyway:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
---
spring:
  profiles: docker
  flyway:
    enabled: true
  datasource:
    url: jdbc:postgresql://172.18.0.2:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
---
spring:
  profiles: test
  flyway:
    enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=- 1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: postgres
    password: postgres
  driver: org.h2.Driver
  classpath: ./lib/h2-1.4.192.jar
  url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=- 1;DB_CLOSE_ON_EXIT=FALSE
  username: postgres
  password: postgres
